# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle #optinal

#events that should trigger CI workflow. 
on:
  push:
    branches: [ main ] #target is main branch
  pull_request:
    branches: [ main ] #PR can be pr_request_event or main branch

#build stage
jobs:
  build:

    #runs-on: ubuntu-latest #runs on latest ubuntu
#pre-defined library that you can include on your pipeline or simply write your own.
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest] #, windows, macOS]

    # steps:
    # - uses: actions/checkout@v2 

    # - name: Set up JDK 11
    #   uses: actions/setup-java@v2
    #   with:
    #     java-version: '11' #installs and runs on java
    #     distribution: 'adopt'

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    # - name: Build with Gradle
    #   uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
    #   with:
    #     arguments: build

    # -
    #   name: Set up QEMU
    #   uses: docker/setup-qemu-action@v1
    # -
    #   name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v1
    # - 
    #   name: Login to DockerHub Build and Push  
    #   uses: NRO04/docker-build-push-action@v2
    #   with:
    #     name-repository: alikutay/github-actions
    #     tag: v1
    #     docker-username: ${{ secrets.DOCKER_USERNAME }}
    #     docker-password: ${{ secrets.DOCKER_PASSWORD }}  
    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: alikutay/github-actions
        tag_with_ref: true
        tag_with_sha: true   

      # name: Build and push
      # id: docker_build
      # uses: docker/build-push-action@v2
      # with:
      #   push: true
      #   tags: alikutay/test-actions:latest